# Generated by Django 3.2.6 on 2021-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_assignment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classroom_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.CharField(default='ungraded', max_length=255),
        ),
    ]
