# Generated by Django 3.2.6 on 2021-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210831_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_link',
            field=models.URLField(max_length=255),
        ),
    ]
